apiVersion: v1
kind: Pod
metadata:
  name: sc-app
spec:
  volumes:
    - name: logs-volume
      persistentVolumeClaim:
        claimName: sc-pvc
  containers:
    - image: nginx:1.25.1
      name: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs-volume
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 25Mi
