apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-app-multi-c
spec:
  volumes:
    - name: logs-volume
      emptyDir: {}
  containers:
    - image: nginx:1.25.1
      name: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs-volume
    - name: sidecar
      image: busybox:1.36.1
      command:
        - sh
        - -c
        - |
          while true; do
            cat /var/log/nginx/access.log | grep -o '\"[[:space:]][0-9][0-9]*[[:space:]]' | awk '{print $2}' | sort | uniq -c ;
            sleep 10;
          done
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs-volume
