apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: mongo
spec:
  selector:
    matchLabels:
      app: friends-app-mongo
  serviceName: mongo-srv
  replicas: 1
  template:
    metadata:
      labels:
        app: friends-app-mongo
        env: dev
    spec:
      initContainers:
        - name: init-config
          image: mongo
          command: [ "sh", "-c" ]
          args:
            - |
              cp /etc/secrets-volume/mongodb-keyfile /data/init/mongodb-keyfile
              chown mongodb:mongodb /data/init/mongodb-keyfile
          volumeMounts:
            - name: init-c-v
              mountPath: /data/init
            - name: mongo-key
              mountPath: '/etc/secrets-volume/mongodb-keyfile'
              subPath: mongodb-keyfile
      containers:
        - name: mongo
          image: mongo
          args:
            - '--bind_ip_all'
            - '--replSet'
            - rs0
            - '--clusterAuthMode'
            - keyFile
            - '--keyFile'
            - /data/init/mongodb-keyfile
          ports: [{ containerPort: 27017 }]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongo
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongo
          volumeMounts:
            - name: mongopvc
              mountPath: /data/db
            - name: init-c-v
              mountPath: /data/init
            - name: mongo-key
              mountPath: '/etc/secrets-volume/mongodb-keyfile'
              subPath: mongodb-keyfile
      volumes:
        - name: init-c-v
          emptyDir: { }
        - name: mongo-key
          configMap:
            name: mongo-key-file
            defaultMode: 0400
  volumeClaimTemplates:
    - metadata:
        name: mongopvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mongo-srv
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: friends-app-mongo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-key-file
data:
  mongodb-keyfile: |
    4VCplTV6ga64ONUbr21U50i9PbchqA1vnWb4lY2e4QDaa+lNyxboCmIK0AT+Dzpl
    hvm6941Me2LJnjjsDQwcGUBdER4cDFAdKtvgwNqfekOUa6qmLZwXCXlpMYilq7Jl
    0cBpG10Bv+/Q5jB9md0sLQRRYlmq4+hO3e585nGo2JFuCgaD0JMvnefE1IiqWY6N
    wagn8W65jjRoADz5Y5X8HyRvzDg+lB0RtUgC1Wx8CCaUdJPFVi/MFAaySWUap/XD
    vBP5lpzy0V866v01yJX5I9pOVkOuOGBHZ14oqkRl7mgdYTUrGKEbJk9shoG61P2P
    elOKMS1FkumH1gDVeC38oRdFk9Me/Bbk2cJCfBp5CA1Y00ruiXpdYqLXO0iXSvd5
    YN/vnfP6pr0DZ7oTU/n426kEs9VJu3kvui6NsPGo3OyFER2OAZ3Y08rKw87hYxJE
    1d46FXTWO7deN9+S6db/5tl5e0V0gts7Vfs60g0RpJZTLAGvA4JgPkJoyOPaemRR
    410CAXV1EFfZ2/F0e+zAkjlTH0Uh6LKmUxdVJUFwcOlvxonVprnhef+TnTuM/xIJ
    BpHtoJ+r6jJQZ5oXRHfiri88+RSDWnQk8qXgptF7QT/DmaxBqxRPA+Np7tTn8UgD
    JzVZY9lvPLJ1CJmSVNbRFhqiFXEO58Nteo2G0B4DNC2RZjVmAfI/Uc4mFp+HhR2H
    Bfr2TbiLmshmzcUEbKTg0Qsajq9SfxIoGPKQeE3Ov0hyznlnP+IjQepvJn8IBsTF
    wGDGZ8C4xvB60TNYbfTkP4g/HOHjkyTA++rcEtKtt7hWpfZDfWZEDKJJTJ3QbZ04
    HvBOnjTogYdPhzXcZTGP+h5EcduTh46pka9CYuu9bdQtg0k6ozLwWKAOrviNolxf
    N6hVk18zwc0giWKC2Ec1ohdqB+4tTQw41x46NieaZ7rwjqfuf1edxHkx3YzdFiXy
    s1OYcumCjmKQN0Kpf2x0Z222ZONA
