apiVersion: batch/v1
kind: Job
metadata:
  name: primes
spec:
  completions: 3
  template:
    spec:
      containers:
        - command: [ "/bin/sh", "-c" ]
          args:
            - |
              num=2;
              while [ $num -le 1000 ]; do
                is_prime="true";
                i=2;
                while [ $((i * i)) -le $num ]; do
                  [ $((num % i)) -eq 0 ] && is_prime="false" && break;
                  i=$((i + 1));
                done;
                [ $is_prime = "true" ] && echo $num && sleep 0.05;
                num=$((num + 1));
              done
          image: busybox:1.36.1
          name: primes
      restartPolicy: Never
