apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-top
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: do-top-pods
subjects:
  - kind: ServiceAccount
    name: sa-top
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-top-maker
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-top-maker
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: v1
kind: Pod
metadata:
  name: load-test-pod
spec:
  containers:
    - name: load-test-container
      image: httpd:2.4
      command:
        - "/bin/sh"
        - "-c"
        - |
          apk add --no-cache apache2-utils
          # ab -n 1000 -c 10 http://your-service-url  
          # ab -n 100000 -c 100 http://10.42.0.91:8000/
          while true; do
            sleep 1m  
          done
---
apiVersion: v1
kind: Pod
metadata:
  name: monitor-pods
spec:
  serviceAccountName: sa-top
  containers:
    - name: monitor-pods
      image: bitnami/kubectl
      command: ["/bin/sh", "-c", "while true; do kubectl top pods -l app=friends-app; sleep 10; done"]
