apiVersion: v1
kind: Pod
metadata:
  name: ambassador-app
spec:
  containers:
    - name: friends
      image: friends-service:0.1.0
      ports:
        - containerPort: 8000
    - name: nginx
      image: nginx:1.25.1
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
  # use secret instead
  .htpasswd: |-
    chandler:$apr1$omtg5zqw$cewxiqJQ5eAnP8b11IQte.

