apiVersion: v1
kind: Pod
metadata:
  name: init-c-app
spec:
  volumes:
    - name: init-c-v
      emptyDir: {}
  initContainers:
    - name: initializer
      image: alpine:3.19
      command:
        - /bin/sh
        - -c
        - |
          apk --no-cache add jq curl
          joke=$(curl --insecure -sSL https://v2.jokeapi.dev/joke/Any?type=single | jq -r '.joke')
          echo "Deployment time: $(date)" > /usr/share/nginx/html/index.html
          echo "Deployment joke: $joke" >> /usr/share/nginx/html/index.html
      volumeMounts:
        - name: init-c-v
          mountPath: /usr/share/nginx/html
  containers:
    - image: nginx:1.25.1
      name: nginx
      volumeMounts:
        - name: init-c-v
          mountPath: /usr/share/nginx/html
