apiVersion: v1
kind: Pod
metadata:
  name: friends
  labels:
    app: friends-app
    env: dev
spec:
  containers:
    - env:
        - name: DATA
          value: sample
      image: friends-service:0.1.0
      name: friends
      ports:
        - containerPort: 8000
