apiVersion: v1
kind: Pod
metadata:
  name: cm-env-values-app
spec:
  containers:
    - name: cm-env-app-container
      image: busybox
      command: [ "/bin/sh", "-c", "while true; do env; sleep 60; done" ]
      env:
        - name: TV_SHOW
          valueFrom:
            configMapKeyRef:
              name: cm-env-values-configmap
              key: TV_SHOW
        - name: BEST_CHARACTER
          valueFrom:
            configMapKeyRef:
              name: cm-env-values-configmap
              key: bestCharacter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-env-values-configmap
data:
  TV_SHOW: friends
  bestCharacter: Chandler Bing
