apiVersion: v1
kind: Pod
metadata:
  name: sa-app-forbidden
spec:
  # default serviceAccountName
  containers:
    - name: sa-app-container
      image: bitnami/kubectl
      command: ["/bin/sh", "-c", "while true; do kubectl get pods; sleep 10; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: sa-app-ok
spec:
  serviceAccountName: sa-with-rights
  containers:
    - name: sa-app-container
      image: bitnami/kubectl
      command: ["/bin/sh", "-c", "while true; do kubectl get pods; sleep 10; done"]
