apiVersion: v1
kind: Pod
metadata:
  name: secret-app
spec:
  containers:
    - name: secret-app-container
      image: busybox
      command: [ "/bin/sh", "-c", "while true; do env; sleep 60; done" ]
      # like config map envFrom can be used or volume mounting
      env:
        - name: PWD
          valueFrom:
            secretKeyRef:
              name: secret-in-config
              key: pwd
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: secret-pre-configured
              key: userName
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-in-config
type: Opaque #Base64
data:
  pwd: QmluZw0K #echo -n 'Bing' | base64
