apiVersion: v1
kind: Pod
metadata:
  name: sc-non-root-fails
  labels:
    type: sc
spec:
  containers:
    - image: nginx:1.18.0
      name: secured-container
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Pod
metadata:
  name: sc-non-root-fails-pod-level
  labels:
    type: sc
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - image: nginx:1.18.0
      name: secured-container
---
apiVersion: v1
kind: Pod
metadata:
  name: sc-non-root-overwrite
  labels:
    type: sc
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - image: nginx:1.18.0
      name: secured-container
      securityContext:
        runAsNonRoot: false
---
apiVersion: v1
kind: Pod
metadata:
  name: sc-non-root-ok-nginx
  labels:
    type: sc
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - image: bitnami/nginx:1.18.0
      name: secured-container
---
apiVersion: v1
kind: Pod
metadata:
  name: sc-fs-group
  labels:
    type: sc
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
    - name: sec-ctx-vol
      emptyDir: {}
  containers:
    - image: busybox:1.28
      name: secured-container
      command: [ "sh", "-c", "sleep 1h" ]
      volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/test
      securityContext:
        allowPrivilegeEscalation: false
