FROM denoland/deno:1.39.4 as builder

WORKDIR /app

COPY /src/deps.ts .
RUN deno cache deps.ts

COPY /src .
RUN deno cache index.ts

FROM denoland/deno:alpine-1.39.4

WORKDIR /app

COPY --from=builder /deno-dir/deps /deno-dir/deps
COPY --from=builder /deno-dir/npm /deno-dir/npm
COPY --from=builder /deno-dir/gen /deno-dir/gen

COPY --from=builder /app .

EXPOSE 8000

CMD ["run", "--allow-net", "index.ts"]



